### PR TITLE
A few fixes/details ironed out.

### PR DESCRIPTION
**Pull request by jrcarl624**
I apologize on the behalf of my formatter, maybe add a linter?

### CODE REVIEW

**Comment by Visual1mpact** [comment]
> I apologize on the behalf of my formatter, maybe add a linter?

Definitely gonna need a linter to keep formatting under control lol. Our formatters are gonna create a lot of clutter real quick haha.

**Comment by Visual1mpact** [comment]
What did you use for your formatting? It made it difficult to review the commits for the actual changes in-between the lines.

**Comment by jrcarl624** [comment]
Prettier, I can re do the commits without formatting.

**Comment by jrcarl624** [comment]
Also that I use " for strings and that auto formats.

**Comment by jrcarl624** [comment]
I feel the best thing we can do here is set up es-lint with the npm package and have something in the package.json

**Pull request closed without merging**
