### PR TITLE
made chat filter able to be disabled

### PR DESCRIPTION
**Pull request by Dreamedc2015**

### CODE REVIEW

**Comment by Visual1mpact** [comment]
Unfortunately, this change won't work. It's in the right direction but needs to be handled differently. Disabling the function for ChatFilter will subsequently break the ability for staff to tag their names using the command !tag <tagname>. Inside the function for ChatFilter it has a hard implementation for filtering the messages being broadcasted. The filter will need to be extracted from that function and isolated elsewhere. I suggest making it into a module using the current module in this patch and mimicking the module for namespoofB for "regex" but an implementation that offers the module control over enabling or disabling it.

**Comment by Dreamedc2015** [comment]
making it configurable isnt actually a bad thing. people may not even want the option to be tagged 

also "chat filter" isnt a really good way to name the thing which does your nicks

**Comment by Visual1mpact** [comment]
They are two separate features built into one single concept. Blocking both for one isn't feasible. Needs to be isolated to be considered. So that both are available.

**Comment by Visual1mpact** [comment]
Closing this pull request since it is inadequate as is and no changes have been made since the initial request.

**Pull request closed without merging**
