### PR TITLE
style fix

### PR DESCRIPTION
**Pull request by Mantou1233**
w

### CODE REVIEW

**Comment by Visual1mpact** [comment]
You are subscribing to the function but not passing the object to the function as a parameter.

**Comment by Mantou1233** [comment]
that also does work

**Comment by Visual1mpact** [comment]
Before:
```World.events.beforeChat.subscribe(msg => prefixcommand(msg));```
After:
```World.events.beforeChat.subscribe(prefixcommand);```

msg would return undefined in

```js
function prefixcommand(msg) {
    const player = msg.sender;

    commandHandler(player, msg);
}
```

**Comment by Mantou1233** [comment]
how would it be undefined? didnt get it
passing the method itself is better than passing a method that calls a method with parms

**Comment by Mantou1233** [comment]
```
function callback(caller, args){
    caller(args)
}
callback(console.log, 1) //1
callback((arg) => console.log(arg), 1) //1
```
they do the same thing

**Comment by Visual1mpact** [comment]
```js
import { world } from "mojang-minecraft";
import { commandHandler } from "../../../commands/handler.js";

const World = world;

function prefixcommand(msg) {
    const player = msg.sender;

    commandHandler(player, msg);
}

const PrefixCommand = () => {
    World.events.beforeChat.subscribe(prefixcommand);
};

export { PrefixCommand };
```

You are subscribing to a function which expects a parameter to be defined. It's not being defined so when the parameter is later used in the function to define the player object it would essentially error.

```msg.sender``` wouldn't return anything because ```msg``` wouldn't have anything to account for it.

It's the same scenario with the other files as well.

**Comment by Mantou1233** [comment]
wdym by expects a parameter to be defined? params are passed to the prefixcommand function
`World.events.beforeChat.subscribe(msg => prefixcommand(msg));` basicly pass a argument and repass that argument to prefixcommand

**Comment by Visual1mpact** [comment]
Yes, but you removed msg from the subscription. msg is the object which triggers the event. The object defines the properties for the message and the entity, specifically the player class, that sent the message. Without the object you cannot call its properties.

**Comment by Mantou1233** [comment]
the object is passed to `function prefixcommand(msg)`'s msg, since it is just calling the method. ive done that a lot and it does always work. >_>

**Comment by Mantou1233** [comment]
it does not expects a parameter to be defined, but pass that param and do the cb, so doing prefixcommand, msg is passed to prefixcommand

**Comment by Visual1mpact** [comment]
I just verified. It works. Though I can't say when this was allowed with Gametest because this wasn't the case for me in the past when I first began working on this project.

**Comment by Mantou1233** [comment]
it always works for me since i started doing gametest ¯\\_(ツ)_/¯. anyways

**Comment by Visual1mpact** [comment]
I find that odd. Nonetheless, you still have a lot of other files that would need similar changes made to them for this patch to be complete.

**Comment by Mantou1233** [comment]
ight

**Comment by Mantou1233** [comment]
image
even you do that yourself ._.

**Comment by Mantou1233** [comment]
ok i think its done

**Comment by Visual1mpact** [comment]
I'll check it out when I get a chance. Just now following up on your last reply.

**Comment by Visual1mpact** [comment]
> image even you do that yourself ._.

That's because the function didn't expect a parameter.

```js
function time() {
    // Code goes here
}
```

**Review by Visual1mpact — APPROVED** [review]

**Pull request merged**
