### PR TITLE
tp module request

### PR DESCRIPTION
**Pull request by Dylanomeneer**
can you add a ¨!hub/main¨ and that you need to edit in the files, or however you want it, or tell me how you add that

if it is possible i just need a simple tp command that works for everyone that just tps you to the ¨!hub¨ instead of me making a backway with commands. idk how the coding works so i have no idea how to add it

### CODE REVIEW

**Comment by Visual1mpact** [comment]
I'm assuming this pull request was unintentional?

**Comment by Dylanomeneer** [comment]
> I'm assuming this pull request was unintentional?

Idk how it works i just wanted to send a request

**Comment by Visual1mpact** [comment]
The pull request section is where you can contribute code by making modifications to the original source and sending a pull request so those changes can be reviewed and discussed as needed. This section on GitHub isn't meant to be used for a typical discussion. I'm no longer developing Paradox so I can't help you with this request. The code is outdated on the latest Bedrock version at the moment and would need to be updated before even considering fullfilling this request. I suggest asking about this on Discord and seeing if maybe Frost will be willing to assist you with his forked project.

**Comment by Dylanomeneer** [comment]
> 

what is the discord then?

**Pull request closed without merging**
